# ST3.Outils.Pipeline.DesinstallerUnArtefact
trigger: none

pool:
  name: Compilation RRQ-AF

name: "Lancer la désinstallation d'un artefact sur les serveurs"
appendCommitMessageToRunName: false

parameters:
  - name: nomArtefact
    displayName: "Nom de l'artefact? (Exemple: FC_Fichier_Inscription_Clientele.Web.20240910.1.Phase6_azure)"
    type: string
    default: ''

  - name: desinstallationNonPhasable
    displayName: Retirer aussi les composants non phasables?
    type: boolean
    default: false

  - name: numeroDemandeChangement
    displayName: Numéro de la demande de changement (obligatoire en PROD, format CHG1234567)
    type: string
    default: ''

extends:
  template: ST3.Outils.Pipeline.DesinstallerUnArtefact.Etapes.yml
  parameters:
    environments:
      - 'UNIT'
      - 'INTG'
      - 'INTH'
      - 'INTX'
      - 'SIMI'
      - 'SIML'
      - 'ACCP'
      - 'FORA'
      - 'PROD'
    nomArtefact: ${{ parameters.nomArtefact }}
    desinstallationNonPhasable: ${{ parameters.desinstallationNonPhasable }}
    numeroDemandeChangement: ${{ parameters.numeroDemandeChangement }}
